### ISSUE TITLE
Django 3.1: Unable to serialize database: from_db_value() missing 1 required positional argument: 'context'

### ISSUE THREAD

**Issue by jayvdb** [ambitioninc/django-regex-field#44]
```py
[   18s] ======================================================================
[   18s] ERROR: Make sure django can serializer the model
[   18s] ----------------------------------------------------------------------
[   18s] Traceback (most recent call last):
[   18s]   File "/usr/lib/python3.8/site-packages/django/core/management/commands/dumpdata.py", line 190, in handle
[   18s]     serializers.serialize(
[   18s]   File "/usr/lib/python3.8/site-packages/django/core/serializers/__init__.py", line 128, in serialize
[   18s]     s.serialize(queryset, **options)
[   18s]   File "/usr/lib/python3.8/site-packages/django/core/serializers/base.py", line 90, in serialize
[   18s]     for count, obj in enumerate(queryset, start=1):
[   18s]   File "/usr/lib/python3.8/site-packages/django/core/management/commands/dumpdata.py", line 178, in get_objects
[   18s]     yield from queryset.iterator()
[   18s]   File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 360, in _iterator
[   18s]     yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
[   18s]   File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 70, in __iter__
[   18s]     for row in compiler.results_iter(results):
[   18s]   File "/usr/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1100, in apply_converters
[   18s]     value = converter(value, expression, connection)
[   18s] TypeError: from_db_value() missing 1 required positional argument: 'context'
[   18s] 
[   18s] During handling of the above exception, another exception occurred:
[   18s] 
[   18s] Traceback (most recent call last):
[   18s]   File "/home/abuild/rpmbuild/BUILD/django-regex-field-1.3.1/regex_field/tests/regex_field_tests.py", line 89, in test_dumpdata
[   18s]     call_command('dumpdata')
[   18s]   File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 168, in call_command
[   18s]     return command.execute(*args, **defaults)
[   18s]   File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
[   18s]     output = self.handle(*args, **options)
[   18s]   File "/usr/lib/python3.8/site-packages/django/core/management/commands/dumpdata.py", line 203, in handle
[   18s]     raise CommandError("Unable to serialize database: %s" % e)
[   18s] django.core.management.base.CommandError: Unable to serialize database: from_db_value() missing 1 required positional argument: 'context'
```

**Comment by wesokes** [comment]
fixed in 2.0.0
